apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-minikube
  namespace: argocd
spec:
  project: default
  source:
    repoURL: file:///Users/mdarafay/Documents/istio-gitops-skeleton/.git
    targetRevision: main
    path: environments/minikube/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
