apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/mdarafay7/istio-gitops-skeleton.git
    targetRevision: main
    path: environments/minikube/namespaces/istio-system
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true